### ISSUE TITLE
Integration in homey

### ISSUE THREAD

**Issue by DrFatalis** [AdyRock/SwitchBotBLEHub#1]
Hi,

I downloaded your project and uploaded it on an ESP32, seems to work perfectly fine. Once done, I added the device in homey as a Curtain Hub.

Device is shown in homey but I cannot send any command as it says that cloud service needs to be enable. I then checked my switchbot app and to enable the cloud service, a hub needs to be in switchbot app....

Did I miss something ?

Thx

**Comment by AdyRock** [comment]
To connect via the ESP32 you need to add the curtain as a BLE device. It basically works as a BLE extender.

**Comment by DrFatalis** [comment]
I currently have both, the official device connected via Bluetooth (ble) and the ESP32 as Curtain (Hub)

Which one is supposed to send the open and close command ?

**Comment by AdyRock** [comment]
If you have added the Curtain (Hub) then it will use the SwitchBot hub and the cloud to connect..
To use the ESP32 module you need to add the Curtain (BLE) device. The app will then try to send the BLE commands through the ESP module if it has detected the curtains, else it will try via Homey's built in BLE.
You can check if the ESP32 has detected the device by pointing your browser at the ESP32's IP address.

**Comment by DrFatalis** [comment]
Summary of what I have:

- homey switchbot app from where I added the curtain 3 BLE
- esp32 with your hub project that detects my curtain 3 BLE
- above esp32 added in homey using the switchbot app (curtain hub) where I entered my account credentials

When using the Hub device added in homey I got the following when I click open / close
[
![Screenshot_20240122-231730](https://github.com/AdyRock/SwitchBotBLEHub/assets/5773055/52ac7292-74a9-4e64-aa8e-5d3f63361949)
](url)

[
![Screenshot_20240122-235918](https://github.com/AdyRock/SwitchBotBLEHub/assets/5773055/b70ede7a-dca3-4006-9b81-849613a27d10)
](url)

**Comment by AdyRock** [comment]
As I said, the ESP32 is not added as a hub, that is only for the Switchbot hub. 

To use the ESP32, you need to add the Curtain (BLE) device. The app will automatically detect the ESP32 and route the BLE commands through it.

So delete the Curtain (Hub) device and add the Curtain (BLE) device.
