### ISSUE TITLE
Question - multiple device supported?

### ISSUE THREAD

**Issue by gtankovics** [AdyRock/SwitchBotBLEHub#2]
I'd like to control curtains in different rooms which are too far from Homey. Is it supported to install a single device in each room and control SwitchBot curtains controller.

**Comment by AdyRock** [comment]
I guess you mean the SwitchBot hubs, in which case yes. You assign the curtains to a hub in the 3rd party setting. 

Also, if you are technically minded, I have code on github for ESP32 modules to act as a BLE bridge for local access between Homey and the curtains

**Comment by gtankovics** [comment]
answered
