### ISSUE TITLE
Not sending data to devices?

### ISSUE THREAD

**Issue by Bjorn-b** [AdyRock/SwitchBotBLEHub#9]
Hi,
I just set this up and successfully added both my curtain3 to homey pro 23. But when I send commands the devices aren't doing anything?
I get data from the devices though as they're showing the correct battery level. Can I troubleshoot what is going on somehow?

I tried sending a POST via postman too, just to exclude Homey, with the same outcome. :(

Best regards,
Björn

**Comment by AdyRock** [comment]
Can you see the ESP32 in a web browser?
If you can, check that it has found your curtains with the list devices page.
It's possible that Homey is using it's own BLE.
You could also check the app settings page and select the Log tab. Set the log level to Detailed Information and then operate the curtains and check the log.

**Comment by Bjorn-b** [comment]
In sweden we have a saying "Skit bakom spakarna", which translates to "Shit behind the wheel". Thanks for the answer and the resolution! Works like a charm!
Love the solution you've built!
